const ItemActionTypes = {
  SET_CURRENT_ITEM: 'SET_CURRENT_ITEM',
  SET_ITEM_NAME: 'SET_ITEM_NAME',
  ROTATE_ITEM: 'ROTATE_ITEM',
  FLIP_X_ITEM: 'FLIP_X_ITEM',
  FLIP_Y_ITEM: 'FLIP_Y_ITEM'
}

export default ItemActionTypes;